### PR TITLE
Fixes for predictive back gesture support

### LINKED ISSUE #36: Problems with android system back not dismissing the sheet
When using the sheet normally, I've had problems with the `onSystemBack = { // this }` not being called at all when the system back is pressed, and instead it is simply doing what it'd do if the sheet wasn't there at all.

I am asking here just to see if this is some known issue, if not I probably should try to make a repro to better explain what I am experiencing and you might just be able to help me by pointing out any obvious mistakes I may be making.

### PR DESCRIPTION
**Pull request by oleksandrbalan**
* Should resolve  #36
* Also fixes incorrect state on the non-cancelable modal sheet, when was hidden externally by setting visible to false
* Bumps to newer stable versions

### CODE REVIEW

File: modalsheet/src/main/java/eu/wewox/modalsheet/ModalSheet.kt [hunk 1]
```diff
@@ -146,8 +150,10 @@ public fun ModalSheet(
 
     LaunchedEffect(visible) {
         if (visible) {
+            internalCancelable.value = cancelable
```
Comment (wooodenleg) [inline modalsheet/src/main/java/eu/wewox/modalsheet/ModalSheet.kt:153]: this launched effect is not re-run when `cancelable` changes but is the only way how `cancelable` can propagate into `internalCancelable`. I don't really know much about this domain to point to a bug right away but looks very error prone

**Review by filwiesner — CHANGES_REQUESTED** [review]

File: modalsheet/src/main/java/eu/wewox/modalsheet/ModalSheet.kt (hunk 1 above)
Comment (oleksandrbalan) [reply modalsheet/src/main/java/eu/wewox/modalsheet/ModalSheet.kt:153]: Thanks for a review 🫶  

Yeah, there could be use-cases where `cancelable` is updated when the sheet is shown, and in this case, it will not work correctly.

I have added `cancelable` to the effect keys. It seems to have fixed the issue with updating the flag. As a small side effect, the `show()` function will be called once more, but that's OK as for me, as it only animates the sheet to the expanded state (which is already expanded).

Additionally, I've re-added the "update parameters" logic to update the back handler as well.

**Review by filwiesner — APPROVED** [review]
Sorry, I don't have time to test this. Just eyeballing it 😅
